import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/shared/Header/Header";
import { MenuProvider } from "@/context/MenuProvider";

export const metadata: Metadata = {
    title: "Photographer",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <MenuProvider>
                    <Header />
                    {children}
                </MenuProvider>
            </body>
        </html>
    );
}
